language: r

cache: packages

sudo: false

r:

  - oldrel

  - release

  - devel

addons:

   apt: 

      packages: libmpfr-dev

warnings_are_errors: true

before_install:

  - tlmgr install index # for texlive and vignette?

  - cd selectiveInference
